version: "3.4"
services:
  database-pharmacy:
    image: postgres:13
    restart: always
    container_name: database-pharmacy
    networks:
      - pharmacy_database_net
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
    ports:
      - "5555:5432"
  integration-tests:
      container_name: integration-tests
      environment:
        DB_USER: "root"
        DB_PASSWORD: "root"
        DB_PORT: "5432"
        DB_NAME: "Pharmacy"
        SERVER: "database-pharmacy"
      networks:
      - pharmacy_database_net
      image: mcr.microsoft.com/dotnet/sdk:3.1
      working_dir: /Pharmacy
      volumes:
      - .:/Pharmacy
      command: bash -c "
        dotnet new tool-manifest --force && 
        dotnet tool install --local dotnet-ef --version 3.1.0 &&
        apt-get update && apt-get -y install libxml2 libgdiplus libc6-dev &&
        dotnet restore Pharmacy &&
        dotnet dotnet-ef migrations add TestingMigration1 --project PharmacyLibrary/ &&
        dotnet dotnet-ef database update --project PharmacyLibrary/ &&
        dotnet test Pharmacy
        "
      depends_on:
        - database-pharmacy
networks:
  pharmacy_database_net:
    name: pharmacy_database_net
    driver: bridge