version: "3.2"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
      POSTGRES_DB: "drugstoredb"
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./scripts/data.sql
        target: /docker-entrypoint-initdb.d/init.sql
    ports: 
      - "5555:5432"
    networks: 
      - network
    
  pharmacy:
      image: student161/drugstore
      container_name: savulja
      build: ../drugstore
      restart: on-failure
      ports:
        - "8081:80"
      networks: 
        - application
        - network
      environment:
        DATABASE_USERNAME: "root"
        DATABASE_PASSWORD: "root"
      depends_on:
        - postgres
  front:
    depends_on:
      - pharmacy
    image: student161/appforpharmacy
    ports:
      - "4201:4200"
    restart: on-failure
    networks:
      - public
      - application
volumes:
  database-data:
networks:
  public:
    driver: bridge
  application:
    driver: bridge
  network:
    driver: bridge
   
