-- Table: public.FeedbackResponses

-- DROP TABLE public."FeedbackResponses";

CREATE TABLE IF NOT EXISTS public."FeedbackResponses"
(
    "FeedbackId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Id" integer NOT NULL,
    "Content" text COLLATE pg_catalog."default",
    "FeedbackResponseDate" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_FeedbackResponses" PRIMARY KEY ("FeedbackId")
)

TABLESPACE pg_default;

-- Table: public.Feedbacks

-- DROP TABLE public."Feedbacks";

CREATE TABLE IF NOT EXISTS public."Feedbacks"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Content" text COLLATE pg_catalog."default",
    "FeedbackDate" text COLLATE pg_catalog."default",
    "HospitalName" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Feedbacks" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

-- Table: public.Hospitals

-- DROP TABLE public."Hospitals";

CREATE TABLE IF NOT EXISTS public."Hospitals"
(
    "HospitalName" text COLLATE pg_catalog."default" NOT NULL,
    "HospitalAddress" text COLLATE pg_catalog."default",
    "HospitalCity" text COLLATE pg_catalog."default",
    "ApiKey" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Hospitals" PRIMARY KEY ("HospitalName")
)

TABLESPACE pg_default;


-- Table: public.Medicines

-- DROP TABLE public."Medicines";

CREATE TABLE IF NOT EXISTS public."Medicines"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default",
    "Manufacturer" text COLLATE pg_catalog."default",
    "MedicineType" integer NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "IsPrescribed" boolean NOT NULL,
    "SideEffects" text COLLATE pg_catalog."default",
    "RecommendedDose" text COLLATE pg_catalog."default",
    "Intensity" double precision NOT NULL,
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_Medicines" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."Notifications"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Title" text COLLATE pg_catalog."default",
    "Content" text COLLATE pg_catalog."default",
    "Date" timestamp without time zone NOT NULL,
    "FileName" text COLLATE pg_catalog."default",
    "Read" boolean NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
)
TABLESPACE pg_default;

-- Table: public.Offers

-- DROP TABLE public."Offers";

CREATE TABLE IF NOT EXISTS public."Offers"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Title" text COLLATE pg_catalog."default",
    "Content" text COLLATE pg_catalog."default",
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Offers" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

INSERT INTO public."Medicines"(
	"Id", "Name", "Manufacturer", "MedicineType", "Description", "IsPrescribed", "SideEffects", "RecommendedDose", "Intensity", "Quantity")
	VALUES (1, 'Brufen', 'Galenika', 0, 'Due to its analgesic effects, ibuprofen is indicated for the relief of mild to moderate pain.', false, 'Nausea, vomiting, diarrhea, flatulence, constipation, dyspepsia, abdominal pain, melena, haematemesis, ulcerative stomatitis, exacerbation of colitis and Crohns disease', '3x1', 800, 75);
INSERT INTO public."Medicines"(
	"Id", "Name", "Manufacturer", "MedicineType", "Description", "IsPrescribed", "SideEffects", "RecommendedDose", "Intensity", "Quantity")
	VALUES (2, 'Paracetamol', 'Galenika', 1, 'Mild analgesic. The use of tablets is recommended for the treatment of painful and febrile conditions.', false, 'Special care should be taken when using paracetamol in patients with reduced liver function or
kidney. The risk of overdose is higher in patients with liver disease resulting from abuse
alcohol, and is not accompanied by cirrhosis of the liver.
The recommended dose should not be exceeded.', '3x1', 500, 80);
INSERT INTO public."Medicines"(
	"Id", "Name", "Manufacturer", "MedicineType", "Description", "IsPrescribed", "SideEffects", "RecommendedDose", "Intensity", "Quantity")
	VALUES (3, 'Amitriptilin', 'Hemofarm', 2, 'The drug is introduced into therapy based on the opinion of a psychiatrist or neuropsychiatrist or neurologist', true, 'There is no indication.', '3x1', 100, 10);
INSERT INTO public."Medicines"(
	"Id", "Name", "Manufacturer", "MedicineType", "Description", "IsPrescribed", "SideEffects", "RecommendedDose", "Intensity", "Quantity")
	VALUES (4, 'Panklav', 'Hemofarm', 2, 'Upper and lower respiratory tract infections (J00-J06.8; J20; J32; J40; J41; J42), Urogenital tract infections (N30, N34; N36; N37; N39), Middle ear infections (H65; H66).', true, 'The most common side effects with Panclav are diarrhea, nausea and vomiting.', '5x1', 200, 100);
INSERT INTO public."Medicines"(
	"Id", "Name", "Manufacturer", "MedicineType", "Description", "IsPrescribed", "SideEffects", "RecommendedDose", "Intensity", "Quantity")
	VALUES (5, 'Caffetine', 'Abela Pharm', 0, 'A combined preparation used for short-term therapy of acute, moderate pain.', false, 'No side effects.', '5x1', 500, 300);


INSERT INTO public."Hospitals"(
	"HospitalName", "HospitalAddress", "HospitalCity", "ApiKey")
	VALUES ('Health', 'Gogoljeva 50', 'Novi Sad', 'kahstgdhip896skh');
INSERT INTO public."Hospitals"(
	"HospitalName", "HospitalAddress", "HospitalCity", "ApiKey")
	VALUES ('Medigroup', 'Nardonog fronta 12', 'Novi Sad', 'ophstgdlip893sii');
INSERT INTO public."Hospitals"(
	"HospitalName", "HospitalAddress", "HospitalCity", "ApiKey")
	VALUES ('Betanija', 'Novosadskog sajma 96', 'Novi Sad', 'plkoihta896l8khg');
INSERT INTO public."Hospitals"(
	"HospitalName", "HospitalAddress", "HospitalCity", "ApiKey")
	VALUES ('Health Medic', 'Narodnog fronta 1', 'Novi Sad', 'lakj7h5sg26sk9j7');
INSERT INTO public."Hospitals"(
	"HospitalName", "HospitalAddress", "HospitalCity", "ApiKey")
	VALUES ('Klinicki centar Vojvodina', 'Hajduk Veljkova 19', 'Novi Sad', 'p0p2u4jiklo9kijl');
INSERT INTO public."Hospitals"(
	"HospitalName", "HospitalAddress", "HospitalCity", "ApiKey")
	VALUES ('MC poliklinika', 'Bulevar Cara Lazara 3', 'Novi Sad', 'lokpi8u8u76t5r4e');

INSERT INTO public."Notifications"(
	"Id", "Title", "Content", "Date", "FileName", "Read")
	VALUES (1, 'New consumption', 'You have new consumption in your Pharmacy folder', 
'2021-12-8 12:13:21', 'MedicationConsumptionReport.pdf', true);
INSERT INTO public."Notifications"(
	"Id", "Title", "Content", "Date", "FileName", "Read")
	VALUES (2, 'New consumption', 'You have new consumption in your Pharmacy folder', 
'2021-12-10 02:43:43', 'MedicationConsumptionReport.pdf', false);

INSERT INTO public."Offers"(
	"Id", "Title", "Content", "StartDate", "EndDate")
	VALUES (1, 'ACTION', 'Discount 15% for all new members', '12.9.2021.', '12.31.2021.');
INSERT INTO public."Offers"(
	"Id", "Title", "Content", "StartDate", "EndDate")
	VALUES (2, 'Offer for our old customers', 'If you are interested, contact us for getting great discounts', '12.20.2021.', '1.31.2022.');
INSERT INTO public."Offers"(
	"Id", "Title", "Content", "StartDate", "EndDate")
	VALUES (3, 'New Years action', 'Surprise for all hospitals, for first 50 customers discount 30%. Happy New Year!', '12.30.2021.', '1.1.2022.');


INSERT INTO public."Feedbacks"(
	"Id", "Content", "FeedbackDate", "HospitalName")
	VALUES (1, 'We are very pleased with your services and products', '12.9.2021.', 'Health');
INSERT INTO public."Feedbacks"(
	"Id", "Content", "FeedbackDate", "HospitalName")
	VALUES (2, 'You should be more careful with delivery', '11.30.2021.', 'Betanija');
INSERT INTO public."Feedbacks"(
	"Id", "Content", "FeedbackDate", "HospitalName")
	VALUES (3, 'Everybody is very friendly and helpful!Awesome staff!!', '12.6.2021.', 'MC poliklinika');
INSERT INTO public."Feedbacks"(
	"Id", "Content", "FeedbackDate", "HospitalName")
	VALUES (4, 'Everybody is friendly and does a good job. I have been using this pharmacy for 20 years and they have done excellent work since day 1! Keep up the good work!', '11.20.2021.', 'Medigroup');



INSERT INTO public."FeedbackResponses"(
	"FeedbackId", "Id", "Content", "FeedbackResponseDate")
	VALUES (1, 1, 'We are glad that you are satisfied', '12.9.2021.');
INSERT INTO public."FeedbackResponses"(
	"FeedbackId", "Id", "Content", "FeedbackResponseDate")
	VALUES (4, 1, 'We are glad that you are satisfied', '12.9.2021.');
INSERT INTO public."FeedbackResponses"(
	"FeedbackId", "Id", "Content", "FeedbackResponseDate")
	VALUES (2, 3, 'We are so sorry to read this! Would you like to contact us so we can try to solve your problem?', '12.1.2021.');
INSERT INTO public."FeedbackResponses"(
	"FeedbackId", "Id", "Content", "FeedbackResponseDate")
	VALUES (3, 4, 'Thank you!', '12.6.2021.');