name: deploy system
on:
  push:
    branches: [feature-serverDeploy] 

jobs:
  build:
    name: Deploy 
    runs-on: ubuntu-latest
    steps:
    - name: Activate deploy.sh script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: sh deploy.sh