name: deploy system
on:
  push:
    branches: [master] 

jobs:
  build:
    name: Deploy 
    runs-on: ubuntu-latest
    steps:
    - name: Activate deploy.sh script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
           BRANCH="master"
           GH_COMPOSE_REPO="https://github.com/pswFirma6/dockerCompose/archive/refs/heads/$%7BBRANCH%7D.tar.gz"
           cd dockerCompose
           curl -L ${GH_COMPOSE_REPO} | tar -xz && \
           mv "$(find . -maxdepth 1 -type d | tail -n 1)" start && \
           cd start/Compose
           docker service rm up_front
           docker service rm up_i_front
           docker service rm up_h_front
           docker service rm up_pharmacy
           docker service rm up_integration
           docker service rm up_hospital
           docker service rm up_postgres
           docker service rm up_i_postgres
           docker service rm up_h_postgres
           docker system prune
           docker stack deploy up --compose-file docker-compose.yml
