name: integration-testing
on:
  push:
    branches: [feature-integrationTests]

jobs:
  Run-Integration-Tests:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIRECTORY: PharmacyLibrary
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: drugstoredb
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      rabbit:
       image: rabbitmq:management-alpine

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dotnet ef
        run: dotnet tool install --global dotnet-ef

      - name: Install dependencies
        run: dotnet restore ${SOLUTION_DIRECTORY}

      - name: Create Migrations
        run:
          dotnet ef migrations add InitialCreate --project .\/${PROJECT_DIRECTORY};
      - name: Update Database
        run: dotnet ef database update --project .\/${PROJECT_DIRECTORY};
      - name: Test
        run: dotnet test . --no-restore --verbosity quiet --filter FullyQualifiedName\!~UnitTests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: root
          POSRGRES_USER: root
          POSTGRES_DB: "drugstoredb"
          RABBITMQ_HOST: rabbit
          RABBITMQ_USERNAME: guest
          RABBITMQ_PASSOWORD: guest