name: Packaging Integration Library

on:
  push:
    branches: [ master, develop, feature-semanticRelease ]
    tags:
    - "*"

env:
 PROJECT-DLL : 'PharmacyLibrary/PharmacyLibrary.csproj'
 GITHUB_TOKEN:    '${{ secrets.GITHUB_TOKEN }}'  
 OUTPUT-DLL-DIR : '${{ github.workspace }}/output'
 NUGET-SOURCE-URL : 'https://nuget.pkg.github.com/pswFirma6/index.json'


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/}" >> $GITHUB_ENV
    - name: Clean
      run: dotnet clean ${{ env.PROJECT-DLL }} && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: nuget restore ${{ env.PROJECT-DLL }}
    - name: Build
      run: dotnet build ${{ env.PROJECT-DLL }} --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test ${{ env.PROJECT-DLL }} --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack ${{ env.PROJECT-DLL }} --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push PharmacyLibrary.${VERSION}.nupkg --source https://nuget.pkg.github.com/drugstore/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
    